import { createFileRoute } from "@tanstack/react-router";
import { AppHeader } from "@/components/AppHeader";
import { SiteFooter } from "@/components/SiteFooter";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Prima Donna AI™" },
      { name: "description", content: "The terms that govern your use of Prima Donna AI™." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader />
      <main className="flex-1 px-6 py-16">
        <article className="mx-auto max-w-3xl">
          <p className="text-xs uppercase tracking-[0.25em] text-primary">Legal</p>
          <h1 className="font-display text-5xl mt-3 mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: July 22, 2026</p>

          <section className="mt-10 space-y-4 text-[15px] leading-relaxed">
            <h2 className="font-display text-2xl">1. Acceptance</h2>
            <p>By creating an account or using Prima Donna AI™ ("the Service"), you agree to these Terms. If you do not agree, do not use the Service.</p>

            <h2 className="font-display text-2xl">2. Eligibility</h2>
            <p>You must be at least 18 and authorized to enter into contracts on behalf of your business. The Elite Circle tier is available by invitation only.</p>

            <h2 className="font-display text-2xl">3. Subscriptions and billing</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Essentials ($97/mo), Pro ($197/mo), and Elite Circle ($497/mo) are billed monthly in advance through Stripe.</li>
              <li>Subscriptions renew automatically until canceled. Cancel any time in Settings; access continues through the end of the paid period.</li>
              <li>Fees are non-refundable except where required by law.</li>
            </ul>

            <h2 className="font-display text-2xl">4. Acceptable use</h2>
            <p>You agree not to: misuse the Service, reverse engineer it, scrape it, share your account, upload unlawful content, or use AI output to harm staff, families, or children. We may suspend accounts that violate these rules.</p>

            <h2 className="font-display text-2xl">5. AI output disclaimer</h2>
            <p>Raven provides strategic guidance generated by AI. It is <strong>not</strong> legal, medical, accounting, tax, licensing, or compliance advice. You are responsible for verifying any recommendation against your state's regulations and your own licensed advisors before acting.</p>

            <h2 className="font-display text-2xl">6. Your content</h2>
            <p>You retain ownership of the information you submit (business data, prompts). You grant us a limited license to process it to operate and improve the Service. We do not use your private business data to train third-party foundation models.</p>

            <h2 className="font-display text-2xl">7. Intellectual property</h2>
            <p>The platform, brand, templates, video content, and the Prima Donna Doctrine are owned by us and protected by law. Pro and Elite templates are licensed for use inside your own business — not for resale or redistribution.</p>

            <h2 className="font-display text-2xl">8. Termination</h2>
            <p>You may close your account at any time. We may suspend or terminate accounts for breach, fraud, abuse, or non-payment.</p>

            <h2 className="font-display text-2xl">9. Warranties and liability</h2>
            <p>The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, our aggregate liability is limited to the fees you paid in the 3 months before the claim. We are not liable for indirect, incidental, or consequential damages.</p>

            <h2 className="font-display text-2xl">10. Governing law</h2>
            <p>These Terms are governed by the laws of the State of Georgia, USA, excluding conflict-of-laws rules. Venue lies in the state and federal courts located in Fulton County, Georgia.</p>

            <h2 className="font-display text-2xl">11. Changes</h2>
            <p>We may update these Terms. Continued use after changes take effect constitutes acceptance.</p>

            <h2 className="font-display text-2xl">12. Contact</h2>
            <p><a href="mailto:hello@thepreschoolprimadonna.com" className="text-primary">hello@thepreschoolprimadonna.com</a></p>
          </section>
        </article>
      </main>
      <SiteFooter />
    </div>
  );
}
