import { createFileRoute } from "@tanstack/react-router";
import { AppHeader } from "@/components/AppHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { LEGAL_LAST_UPDATED } from "@/lib/legal";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Preschool Pro AI™" },
      { name: "description", content: "The terms that govern your use of Preschool Pro AI™." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader />
      <main className="flex-1 px-6 py-16">
        <article className="mx-auto max-w-3xl">
          <p className="text-xs uppercase tracking-[0.25em] text-primary">Legal</p>
          <h1 className="font-display text-5xl mt-3 mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: {LEGAL_LAST_UPDATED}</p>

          <section className="mt-10 space-y-4 text-[15px] leading-relaxed">
            <h2 className="font-display text-2xl">1. Acceptance</h2>
            <p>
              Preschool Pro AI™ is owned, operated, and managed by Classroom Panda LLC
              ("Classroom Panda," "we," "us," or "our"). By creating an account or using Preschool
              Pro AI™ ("the Service"), you agree to these Terms. If you do not agree, do not use
              the Service.
            </p>

            <h2 className="font-display text-2xl">2. Eligibility</h2>
            <p>
              You must be at least 18 and authorized to enter into contracts on behalf of your
              business. The Elite Circle tier is available by invitation only.
            </p>

            <h2 className="font-display text-2xl">3. Subscriptions and billing</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                Memberships purchased on the Preschool Pro AI website are billed monthly in advance
                through Stripe. The native iOS app does not collect payment-card details or process
                membership purchases.
              </li>
              <li>
                Subscriptions renew automatically until canceled. Manage a web membership through
                the website billing settings or contact info@classroompanda.com; access continues
                through the end of the paid period.
              </li>
              <li>Fees are non-refundable except where required by law.</li>
            </ul>

            <h2 className="font-display text-2xl">4. Acceptable use</h2>
            <p>
              You agree not to: misuse the Service, reverse engineer it, scrape it, share your
              account, upload unlawful content, or use AI output to harm staff, families, or
              children. We may suspend accounts that violate these rules.
            </p>

            <h2 className="font-display text-2xl">4A. Community standards</h2>
            <p>
              Elite Circle conversations may contain member-submitted text and images. You may not
              post harassment, threats, hate speech, sexual content, child exploitation material,
              private information shared without permission, spam, fraud, intellectual-property
              violations, or other unlawful or objectionable content. Members can report content and
              users. We may review, restrict, remove, or preserve reported content and suspend
              accounts when reasonably necessary for safety, moderation, legal compliance, or
              enforcement of these Terms.
            </p>

            <h2 className="font-display text-2xl">5. AI output disclaimer</h2>
            <p>
              Raven provides strategic guidance generated by AI. It is <strong>not</strong> legal,
              medical, accounting, tax, licensing, or compliance advice. You are responsible for
              verifying any recommendation against your state's regulations and your own licensed
              advisors before acting.
            </p>

            <h2 className="font-display text-2xl">6. Your content</h2>
            <p>
              You retain ownership of the information you submit (business data, prompts). You grant
              us a limited license to process it to operate and improve the Service. We do not use
              your private business data to train third-party foundation models.
            </p>

            <h2 className="font-display text-2xl">7. Intellectual property</h2>
            <p>
              The platform, Preschool Pro AI brand, proprietary coaching frameworks, templates,
              and video content are owned by Classroom Panda LLC and protected by law. Pro and
              Elite templates are licensed for use inside your own business — not for resale or
              redistribution.
            </p>

            <h2 className="font-display text-2xl">8. Termination</h2>
            <p>
              You may close your account at any time. We may suspend or terminate accounts for
              breach, fraud, abuse, or non-payment.
            </p>

            <h2 className="font-display text-2xl">9. Warranties and liability</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. To the maximum extent
              permitted by law, our aggregate liability is limited to the fees you paid in the 3
              months before the claim. We are not liable for indirect, incidental, or consequential
              damages.
            </p>

            <h2 className="font-display text-2xl">10. Governing law</h2>
            <p>
              These Terms are governed by the laws of the State of Georgia, USA, excluding
              conflict-of-laws rules. Venue lies in the state and federal courts located in Fulton
              County, Georgia.
            </p>

            <h2 className="font-display text-2xl">11. Changes</h2>
            <p>
              We may update these Terms. When a material or versioned update requires renewed
              acceptance, the Service will ask you to review and affirmatively agree before
              continuing.
            </p>

            <h2 className="font-display text-2xl">12. Contact</h2>
            <p>
              <a href="mailto:info@classroompanda.com" className="text-primary">
                info@classroompanda.com
              </a>
            </p>
          </section>
        </article>
      </main>
      <SiteFooter />
    </div>
  );
}
