/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplyEliteRouteImport } from './routes/apply-elite'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsStreamRouteImport } from './routes/api/tts-stream'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedEliteRouteImport } from './routes/_authenticated/elite'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedEliteGateRouteImport } from './routes/_authenticated/_elite-gate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as ApiPublicEliteApplyRouteImport } from './routes/api/public/elite-apply'
import { Route as AuthenticatedEliteGateEliteScheduleRouteImport } from './routes/_authenticated/_elite-gate.elite-schedule'
import { Route as AuthenticatedEliteGateEliteCircleRouteImport } from './routes/_authenticated/_elite-gate.elite-circle'
import { Route as AuthenticatedAdminAdminAnalyticsRouteImport } from './routes/_authenticated/_admin/admin-analytics'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as ApiPublicHooksGenerateDailyRecommendationsRouteImport } from './routes/api/public/hooks/generate-daily-recommendations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyEliteRoute = ApplyEliteRouteImport.update({
  id: '/apply-elite',
  path: '/apply-elite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/api/tts-stream',
  path: '/api/tts-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEliteRoute = AuthenticatedEliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEliteGateRoute = AuthenticatedEliteGateRouteImport.update({
  id: '/_elite-gate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicEliteApplyRoute = ApiPublicEliteApplyRouteImport.update({
  id: '/api/public/elite-apply',
  path: '/api/public/elite-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEliteGateEliteScheduleRoute =
  AuthenticatedEliteGateEliteScheduleRouteImport.update({
    id: '/elite-schedule',
    path: '/elite-schedule',
    getParentRoute: () => AuthenticatedEliteGateRoute,
  } as any)
const AuthenticatedEliteGateEliteCircleRoute =
  AuthenticatedEliteGateEliteCircleRouteImport.update({
    id: '/elite-circle',
    path: '/elite-circle',
    getParentRoute: () => AuthenticatedEliteGateRoute,
  } as any)
const AuthenticatedAdminAdminAnalyticsRoute =
  AuthenticatedAdminAdminAnalyticsRouteImport.update({
    id: '/admin-analytics',
    path: '/admin-analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHooksGenerateDailyRecommendationsRoute =
  ApiPublicHooksGenerateDailyRecommendationsRouteImport.update({
    id: '/api/public/hooks/generate-daily-recommendations',
    path: '/api/public/hooks/generate-daily-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/apply-elite': typeof ApplyEliteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/elite': typeof AuthenticatedEliteRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/admin-analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/elite-circle': typeof AuthenticatedEliteGateEliteCircleRoute
  '/elite-schedule': typeof AuthenticatedEliteGateEliteScheduleRoute
  '/api/public/elite-apply': typeof ApiPublicEliteApplyRoute
  '/api/public/hooks/generate-daily-recommendations': typeof ApiPublicHooksGenerateDailyRecommendationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/apply-elite': typeof ApplyEliteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/elite': typeof AuthenticatedEliteRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/admin-analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/elite-circle': typeof AuthenticatedEliteGateEliteCircleRoute
  '/elite-schedule': typeof AuthenticatedEliteGateEliteScheduleRoute
  '/api/public/elite-apply': typeof ApiPublicEliteApplyRoute
  '/api/public/hooks/generate-daily-recommendations': typeof ApiPublicHooksGenerateDailyRecommendationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/apply-elite': typeof ApplyEliteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_elite-gate': typeof AuthenticatedEliteGateRouteWithChildren
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/elite': typeof AuthenticatedEliteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/admin-analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/_authenticated/_elite-gate/elite-circle': typeof AuthenticatedEliteGateEliteCircleRoute
  '/_authenticated/_elite-gate/elite-schedule': typeof AuthenticatedEliteGateEliteScheduleRoute
  '/api/public/elite-apply': typeof ApiPublicEliteApplyRoute
  '/api/public/hooks/generate-daily-recommendations': typeof ApiPublicHooksGenerateDailyRecommendationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/apply-elite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/coach'
    | '/dashboard'
    | '/elite'
    | '/settings'
    | '/templates'
    | '/api/tts-stream'
    | '/admin'
    | '/admin-analytics'
    | '/elite-circle'
    | '/elite-schedule'
    | '/api/public/elite-apply'
    | '/api/public/hooks/generate-daily-recommendations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/apply-elite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/coach'
    | '/dashboard'
    | '/elite'
    | '/settings'
    | '/templates'
    | '/api/tts-stream'
    | '/admin'
    | '/admin-analytics'
    | '/elite-circle'
    | '/elite-schedule'
    | '/api/public/elite-apply'
    | '/api/public/hooks/generate-daily-recommendations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/apply-elite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/_admin'
    | '/_authenticated/_elite-gate'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/elite'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/api/tts-stream'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/admin-analytics'
    | '/_authenticated/_elite-gate/elite-circle'
    | '/_authenticated/_elite-gate/elite-schedule'
    | '/api/public/elite-apply'
    | '/api/public/hooks/generate-daily-recommendations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApplyEliteRoute: typeof ApplyEliteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
  ApiPublicEliteApplyRoute: typeof ApiPublicEliteApplyRoute
  ApiPublicHooksGenerateDailyRecommendationsRoute: typeof ApiPublicHooksGenerateDailyRecommendationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-elite': {
      id: '/apply-elite'
      path: '/apply-elite'
      fullPath: '/apply-elite'
      preLoaderRoute: typeof ApplyEliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-stream': {
      id: '/api/tts-stream'
      path: '/api/tts-stream'
      fullPath: '/api/tts-stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/elite': {
      id: '/_authenticated/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof AuthenticatedEliteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_elite-gate': {
      id: '/_authenticated/_elite-gate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedEliteGateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/elite-apply': {
      id: '/api/public/elite-apply'
      path: '/api/public/elite-apply'
      fullPath: '/api/public/elite-apply'
      preLoaderRoute: typeof ApiPublicEliteApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_elite-gate/elite-schedule': {
      id: '/_authenticated/_elite-gate/elite-schedule'
      path: '/elite-schedule'
      fullPath: '/elite-schedule'
      preLoaderRoute: typeof AuthenticatedEliteGateEliteScheduleRouteImport
      parentRoute: typeof AuthenticatedEliteGateRoute
    }
    '/_authenticated/_elite-gate/elite-circle': {
      id: '/_authenticated/_elite-gate/elite-circle'
      path: '/elite-circle'
      fullPath: '/elite-circle'
      preLoaderRoute: typeof AuthenticatedEliteGateEliteCircleRouteImport
      parentRoute: typeof AuthenticatedEliteGateRoute
    }
    '/_authenticated/_admin/admin-analytics': {
      id: '/_authenticated/_admin/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/generate-daily-recommendations': {
      id: '/api/public/hooks/generate-daily-recommendations'
      path: '/api/public/hooks/generate-daily-recommendations'
      fullPath: '/api/public/hooks/generate-daily-recommendations'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailyRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminAdminAnalyticsRoute: typeof AuthenticatedAdminAdminAnalyticsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminAdminAnalyticsRoute: AuthenticatedAdminAdminAnalyticsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEliteGateRouteChildren {
  AuthenticatedEliteGateEliteCircleRoute: typeof AuthenticatedEliteGateEliteCircleRoute
  AuthenticatedEliteGateEliteScheduleRoute: typeof AuthenticatedEliteGateEliteScheduleRoute
}

const AuthenticatedEliteGateRouteChildren: AuthenticatedEliteGateRouteChildren =
  {
    AuthenticatedEliteGateEliteCircleRoute:
      AuthenticatedEliteGateEliteCircleRoute,
    AuthenticatedEliteGateEliteScheduleRoute:
      AuthenticatedEliteGateEliteScheduleRoute,
  }

const AuthenticatedEliteGateRouteWithChildren =
  AuthenticatedEliteGateRoute._addFileChildren(
    AuthenticatedEliteGateRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedEliteGateRoute: typeof AuthenticatedEliteGateRouteWithChildren
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEliteRoute: typeof AuthenticatedEliteRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedEliteGateRoute: AuthenticatedEliteGateRouteWithChildren,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEliteRoute: AuthenticatedEliteRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApplyEliteRoute: ApplyEliteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiTtsStreamRoute: ApiTtsStreamRoute,
  ApiPublicEliteApplyRoute: ApiPublicEliteApplyRoute,
  ApiPublicHooksGenerateDailyRecommendationsRoute:
    ApiPublicHooksGenerateDailyRecommendationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
